apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: slave-svc
    app.kubernetes.io/instance: test-project
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-project
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
  template:
    metadata:
      name: slave
      labels:
        app: test-project
        tier: backend
    spec:
      containers:
      - name: master
        image: slave:latest
        # TODO: Remove this if image is pushed on registry
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: core-config
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
          privileged: false
          procMount: Default
